#ifndef GAMEPAD
#define GAMEPAD

#include <cstdint>

#define GAMEPAD_MASK_UP     (1U << 0)
#define GAMEPAD_MASK_DOWN   (1U << 1)
#define GAMEPAD_MASK_LEFT   (1U << 2)
#define GAMEPAD_MASK_RIGHT  (1U << 3)
#define GAMEPAD_MASK_B1     (1U << 4)
#define GAMEPAD_MASK_B2     (1U << 5)
#define GAMEPAD_MASK_B3     (1U << 7)
#define GAMEPAD_MASK_B4     (1U << 8)
#define GAMEPAD_MASK_L1     (1U << 9)
#define GAMEPAD_MASK_R1     (1U << 10)
#define GAMEPAD_MASK_L2     (1U << 11)
#define GAMEPAD_MASK_R2     (1U << 12)
#define GAMEPAD_MASK_S1     (1U << 13)
#define GAMEPAD_MASK_S2     (1U << 14)
#define GAMEPAD_MASK_L3     (1U << 15)
#define GAMEPAD_MASK_R3     (1U << 16)
#define GAMEPAD_MASK_A1     (1U << 17)
#define GAMEPAD_MASK_A2     (1U << 18)

const uint32_t buttonMasks[] =
{
    GAMEPAD_MASK_UP,
	GAMEPAD_MASK_DOWN,
	GAMEPAD_MASK_LEFT,
	GAMEPAD_MASK_RIGHT,
	GAMEPAD_MASK_B1,
	GAMEPAD_MASK_B2,
	GAMEPAD_MASK_B3,
	GAMEPAD_MASK_B4,
	GAMEPAD_MASK_L1,
	GAMEPAD_MASK_R1,
	GAMEPAD_MASK_L2,
	GAMEPAD_MASK_R2,
	GAMEPAD_MASK_S1,
	GAMEPAD_MASK_S2,
	GAMEPAD_MASK_L3,
	GAMEPAD_MASK_R3,
	GAMEPAD_MASK_A1,
	GAMEPAD_MASK_A2
};

#endif